// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_codegen.cpp:454

#ifndef _TAO_IDL_SQPSOLVERS_GMXUHQ_H_
#define _TAO_IDL_SQPSOLVERS_GMXUHQ_H_


#include "SqpSolverC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayBoolean>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayBoolean,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayChar>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayChar,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayShort>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayShort,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayLong>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayLong,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayFloat>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayFloat,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayDouble>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayDouble,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayString>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayString,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayVariant>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayVariant,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayInterface>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayInterface,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class SArg_Traits< ::SqpSolver::CapePublicParameter>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapePublicParameter,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::CapeArrayPublicParameter>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::CapeArrayPublicParameter,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:889

  

  template<>
  class SArg_Traits< ::SqpSolver::ParameterType>
    : public
        Basic_SArg_Traits_T<
            ::SqpSolver::ParameterType,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:1041

  

  template<>
  class SArg_Traits< ::SqpSolver::ParameterValue>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::ParameterValue,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class SArg_Traits< ::SqpSolver::SolverParameterDescription>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::SolverParameterDescription,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::SolverParameterDescriptionSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::SolverParameterDescriptionSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class SArg_Traits< ::SqpSolver::SolverParameter>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::SolverParameter,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::SolverParameterSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::SolverParameterSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class SArg_Traits< ::SqpSolver::SolutionResult>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::SolutionResult,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class SArg_Traits< ::SqpSolver::SolutionResultSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::SqpSolver::SolutionResultSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ICAPEMINLP__SARG_TRAITS_)
#define _SQPSOLVER_ICAPEMINLP__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SqpSolver::ICapeMINLP>
    : public Object_SArg_Traits_T<
        ::SqpSolver::ICapeMINLP_ptr,
        ::SqpSolver::ICapeMINLP_var,
        ::SqpSolver::ICapeMINLP_out,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ICAPEMINLPSYSTEM__SARG_TRAITS_)
#define _SQPSOLVER_ICAPEMINLPSYSTEM__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SqpSolver::ICapeMINLPSystem>
    : public Object_SArg_Traits_T<
        ::SqpSolver::ICapeMINLPSystem_ptr,
        ::SqpSolver::ICapeMINLPSystem_var,
        ::SqpSolver::ICapeMINLPSystem_out,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ICAPEMINLPSOLVERMANAGER__SARG_TRAITS_)
#define _SQPSOLVER_ICAPEMINLPSOLVERMANAGER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SqpSolver::ICapeMINLPSolverManager>
    : public Object_SArg_Traits_T<
        ::SqpSolver::ICapeMINLPSolverManager_ptr,
        ::SqpSolver::ICapeMINLPSolverManager_var,
        ::SqpSolver::ICapeMINLPSolverManager_out,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ISOLVERPARAMETERTUNER__SARG_TRAITS_)
#define _SQPSOLVER_ISOLVERPARAMETERTUNER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SqpSolver::ISolverParameterTuner>
    : public Object_SArg_Traits_T<
        ::SqpSolver::ISolverParameterTuner_ptr,
        ::SqpSolver::ISolverParameterTuner_var,
        ::SqpSolver::ISolverParameterTuner_out,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_IINITIALVALUEFINDER__SARG_TRAITS_)
#define _SQPSOLVER_IINITIALVALUEFINDER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SqpSolver::IInitialValueFinder>
    : public Object_SArg_Traits_T<
        ::SqpSolver::IInitialValueFinder_ptr,
        ::SqpSolver::IInitialValueFinder_var,
        ::SqpSolver::IInitialValueFinder_out,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_SqpSolver
{
  

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_sh.cpp:72

  

  class ICapeMINLP;
  typedef ICapeMINLP *ICapeMINLP_ptr;

  class  ICapeMINLP
    : public virtual PortableServer::ServantBase
  {
  protected:
    ICapeMINLP ();
  
  public:
    /// Useful for template programming.
    typedef ::SqpSolver::ICapeMINLP _stub_type;
    typedef ::SqpSolver::ICapeMINLP_ptr _stub_ptr_type;
    typedef ::SqpSolver::ICapeMINLP_var _stub_var_type;

    ICapeMINLP (const ICapeMINLP& rhs);
    virtual ~ICapeMINLP () = default;

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SqpSolver::ICapeMINLP *_this ();
    
    virtual const char* _interface_repository_id () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPSize (
      ::SqpSolver::CapeLong_out nv,
      ::SqpSolver::CapeLong_out niv,
      ::SqpSolver::CapeLong_out nlv,
      ::SqpSolver::CapeLong_out nliv,
      ::SqpSolver::CapeLong_out nc,
      ::SqpSolver::CapeLong_out nlc,
      ::SqpSolver::CapeLong_out nlz,
      ::SqpSolver::CapeLong_out nnz,
      ::SqpSolver::CapeLong_out nlzof,
      ::SqpSolver::CapeLong_out nnzof) = 0;

    static void GetMINLPSize_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPStructure (
      const char * structuretype,
      ::SqpSolver::CapeArrayLong_out rowindex,
      ::SqpSolver::CapeArrayLong_out columnindex,
      ::SqpSolver::CapeArrayLong_out objindex) = 0;

    static void GetMINLPStructure_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPVariableNames (
      const ::SqpSolver::CapeArrayLong & vids,
      ::SqpSolver::CapeArrayString_out vnames) = 0;

    static void GetMINLPVariableNames_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPVariableDoubleAttribute (
      const ::SqpSolver::CapeArrayLong & vids,
      const char * attrib,
      ::SqpSolver::CapeArrayDouble_out values) = 0;

    static void GetMINLPVariableDoubleAttribute_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPVariableBounds (
      const ::SqpSolver::CapeArrayLong & vids,
      ::SqpSolver::CapeArrayDouble_out lb,
      ::SqpSolver::CapeArrayDouble_out ub) = 0;

    static void GetMINLPVariableBounds_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPVariableValues (
      const ::SqpSolver::CapeArrayLong & vids,
      ::SqpSolver::CapeArrayDouble_out values) = 0;

    static void GetMINLPVariableValues_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void SetMINLPVariableValues (
      const ::SqpSolver::CapeArrayLong & vids,
      const ::SqpSolver::CapeArrayDouble & values) = 0;

    static void SetMINLPVariableValues_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPConstraintNames (
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayString_out cnames) = 0;

    static void GetMINLPConstraintNames_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPConstraintBounds (
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayDouble_out lb,
      ::SqpSolver::CapeArrayDouble_out ub) = 0;

    static void GetMINLPConstraintBounds_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPConstraintDoubleAttribute (
      const ::SqpSolver::CapeArrayLong & cids,
      const char * attrib,
      ::SqpSolver::CapeArrayDouble_out values) = 0;

    static void GetMINLPConstraintDoubleAttribute_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPNonlinearConstraintValues (
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayDouble_out values) = 0;

    static void GetMINLPNonlinearConstraintValues_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPConstraintDerivativeValues (
      const char * structtype,
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayDouble_out vals) = 0;

    static void GetMINLPConstraintDerivativeValues_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPNonlinearObjectiveFunctionValue (
      ::SqpSolver::CapeDouble_out value) = 0;

    static void GetMINLPNonlinearObjectiveFunctionValue_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPObjectiveFunctionDerivativeValues (
      const char * stype,
      ::SqpSolver::CapeArrayDouble_out v) = 0;

    static void GetMINLPObjectiveFunctionDerivativeValues_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPObjectiveFunctionDoubleAttribute (
      const char * attrib,
      ::SqpSolver::CapeDouble_out value) = 0;

    static void GetMINLPObjectiveFunctionDoubleAttribute_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void SetMINLPLagrangeMultipliers (
      const char * lmtype,
      const ::SqpSolver::CapeArrayLong & ids,
      const ::SqpSolver::CapeArrayDouble & values) = 0;

    static void SetMINLPLagrangeMultipliers_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetMINLPLagrangeMultipliers (
      const char * lmtype,
      const ::SqpSolver::CapeArrayLong & ids,
      ::SqpSolver::CapeArrayDouble_out values) = 0;

    static void GetMINLPLagrangeMultipliers_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_sh.cpp:72

  

  class ICapeMINLPSystem;
  typedef ICapeMINLPSystem *ICapeMINLPSystem_ptr;

  class  ICapeMINLPSystem
    : public virtual PortableServer::ServantBase
  {
  protected:
    ICapeMINLPSystem ();
  
  public:
    /// Useful for template programming.
    typedef ::SqpSolver::ICapeMINLPSystem _stub_type;
    typedef ::SqpSolver::ICapeMINLPSystem_ptr _stub_ptr_type;
    typedef ::SqpSolver::ICapeMINLPSystem_var _stub_var_type;

    ICapeMINLPSystem (const ICapeMINLPSystem& rhs);
    virtual ~ICapeMINLPSystem () = default;

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SqpSolver::ICapeMINLPSystem *_this ();
    
    virtual const char* _interface_repository_id () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetParameters (
      ::SqpSolver::SolverParameterDescriptionSeq_out parameters) = 0;

    static void GetParameters_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void Solve () = 0;

    static void Solve_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void SetParameters (
      const ::SqpSolver::SolverParameterDescriptionSeq & parameters) = 0;

    static void SetParameters_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void SetProblemID (
      ::SqpSolver::CapeLong id) = 0;

    static void SetProblemID_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_sh.cpp:72

  

  class ICapeMINLPSolverManager;
  typedef ICapeMINLPSolverManager *ICapeMINLPSolverManager_ptr;

  class  ICapeMINLPSolverManager
    : public virtual PortableServer::ServantBase
  {
  protected:
    ICapeMINLPSolverManager ();
  
  public:
    /// Useful for template programming.
    typedef ::SqpSolver::ICapeMINLPSolverManager _stub_type;
    typedef ::SqpSolver::ICapeMINLPSolverManager_ptr _stub_ptr_type;
    typedef ::SqpSolver::ICapeMINLPSolverManager_var _stub_var_type;

    ICapeMINLPSolverManager (const ICapeMINLPSolverManager& rhs);
    virtual ~ICapeMINLPSolverManager () = default;

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SqpSolver::ICapeMINLPSolverManager *_this ();
    
    virtual const char* _interface_repository_id () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void CreateMINLPSystem (
      ::SqpSolver::ICapeMINLP_ptr theMINLP,
      ::SqpSolver::ICapeMINLPSystem_out theMINLPSystem) = 0;

    static void CreateMINLPSystem_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_sh.cpp:72

  

  class ISolverParameterTuner;
  typedef ISolverParameterTuner *ISolverParameterTuner_ptr;

  class  ISolverParameterTuner
    : public virtual PortableServer::ServantBase
  {
  protected:
    ISolverParameterTuner ();
  
  public:
    /// Useful for template programming.
    typedef ::SqpSolver::ISolverParameterTuner _stub_type;
    typedef ::SqpSolver::ISolverParameterTuner_ptr _stub_ptr_type;
    typedef ::SqpSolver::ISolverParameterTuner_var _stub_var_type;

    ISolverParameterTuner (const ISolverParameterTuner& rhs);
    virtual ~ISolverParameterTuner () = default;

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SqpSolver::ISolverParameterTuner *_this ();
    
    virtual const char* _interface_repository_id () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void SetParameterTuningTask (
      const ::SqpSolver::SolverParameterDescriptionSeq & parameterList,
      ::SqpSolver::CapeLong numOfOptCases) = 0;

    static void SetParameterTuningTask_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetNewParameters (
      const ::SqpSolver::SolutionResultSeq & solutionResult,
      const char * method,
      ::SqpSolver::SolverParameterSeq_out newParamters) = 0;

    static void GetNewParameters_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_sh.cpp:72

  

  class IInitialValueFinder;
  typedef IInitialValueFinder *IInitialValueFinder_ptr;

  class  IInitialValueFinder
    : public virtual PortableServer::ServantBase
  {
  protected:
    IInitialValueFinder ();
  
  public:
    /// Useful for template programming.
    typedef ::SqpSolver::IInitialValueFinder _stub_type;
    typedef ::SqpSolver::IInitialValueFinder_ptr _stub_ptr_type;
    typedef ::SqpSolver::IInitialValueFinder_var _stub_var_type;

    IInitialValueFinder (const IInitialValueFinder& rhs);
    virtual ~IInitialValueFinder () = default;

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SqpSolver::IInitialValueFinder *_this ();
    
    virtual const char* _interface_repository_id () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void Initialize (
      ::SqpSolver::CapeLong numOfTotalVariables,
      ::SqpSolver::CapeLong numOfKeyVariables,
      const ::SqpSolver::CapeArrayLong & keyVariableIndices,
      const ::SqpSolver::CapeArrayLong & keyVarMeasurementIndices) = 0;

    static void Initialize_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_operation\operation_sh.cpp:35

    virtual void GetInitialValue (
      const ::SqpSolver::CapeArrayDouble & keyVariableValues,
      const ::SqpSolver::CapeArrayDouble & keyVarMeasurementValues,
      ::SqpSolver::CapeArrayDouble_out newInitialValues) = 0;

    static void GetInitialValue_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module SqpSolver

#endif /* ifndef */

