// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_codegen.cpp:148

#ifndef _TAO_IDL_SQPSOLVERC_0FX4U2_H_
#define _TAO_IDL_SQPSOLVERC_0FX4U2_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_root\root_ch.cpp:155


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace SqpSolver
{
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Boolean CapeBoolean;
  typedef ::CORBA::Boolean_out CapeBoolean_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeBoolean;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYBOOLEAN_CH_)
#define _SQPSOLVER_CAPEARRAYBOOLEAN_CH_

  class CapeArrayBoolean;
  typedef ::TAO_FixedSeq_Var_T<CapeArrayBoolean> CapeArrayBoolean_var;
  typedef ::TAO_Seq_Out_T<CapeArrayBoolean> CapeArrayBoolean_out;
  

  class  CapeArrayBoolean
    : public
        ::TAO::unbounded_value_sequence< CapeBoolean>
  {
  public:
    CapeArrayBoolean () = default;
    CapeArrayBoolean (::CORBA::ULong max);
    CapeArrayBoolean (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Boolean* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayBoolean (const CapeArrayBoolean &) = default;
    CapeArrayBoolean (CapeArrayBoolean &&) = default;
    CapeArrayBoolean& operator= (const CapeArrayBoolean &) = default;
    CapeArrayBoolean& operator= (CapeArrayBoolean &&) = default;
    virtual ~CapeArrayBoolean () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayBoolean_var;
    using _out_type = CapeArrayBoolean_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayBoolean;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Char CapeChar;
  typedef ::CORBA::Char_out CapeChar_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeChar;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYCHAR_CH_)
#define _SQPSOLVER_CAPEARRAYCHAR_CH_

  class CapeArrayChar;
  typedef ::TAO_FixedSeq_Var_T<CapeArrayChar> CapeArrayChar_var;
  typedef ::TAO_Seq_Out_T<CapeArrayChar> CapeArrayChar_out;
  

  class  CapeArrayChar
    : public
        ::TAO::unbounded_value_sequence< CapeChar>
  {
  public:
    CapeArrayChar () = default;
    CapeArrayChar (::CORBA::ULong max);
    CapeArrayChar (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayChar (const CapeArrayChar &) = default;
    CapeArrayChar (CapeArrayChar &&) = default;
    CapeArrayChar& operator= (const CapeArrayChar &) = default;
    CapeArrayChar& operator= (CapeArrayChar &&) = default;
    virtual ~CapeArrayChar () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayChar_var;
    using _out_type = CapeArrayChar_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayChar;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Short CapeShort;
  typedef ::CORBA::Short_out CapeShort_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeShort;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYSHORT_CH_)
#define _SQPSOLVER_CAPEARRAYSHORT_CH_

  class CapeArrayShort;
  typedef ::TAO_FixedSeq_Var_T<CapeArrayShort> CapeArrayShort_var;
  typedef ::TAO_Seq_Out_T<CapeArrayShort> CapeArrayShort_out;
  

  class  CapeArrayShort
    : public
        ::TAO::unbounded_value_sequence< CapeShort>
  {
  public:
    CapeArrayShort () = default;
    CapeArrayShort (::CORBA::ULong max);
    CapeArrayShort (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Short* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayShort (const CapeArrayShort &) = default;
    CapeArrayShort (CapeArrayShort &&) = default;
    CapeArrayShort& operator= (const CapeArrayShort &) = default;
    CapeArrayShort& operator= (CapeArrayShort &&) = default;
    virtual ~CapeArrayShort () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayShort_var;
    using _out_type = CapeArrayShort_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayShort;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Long CapeLong;
  typedef ::CORBA::Long_out CapeLong_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeLong;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYLONG_CH_)
#define _SQPSOLVER_CAPEARRAYLONG_CH_

  class CapeArrayLong;
  typedef ::TAO_FixedSeq_Var_T<CapeArrayLong> CapeArrayLong_var;
  typedef ::TAO_Seq_Out_T<CapeArrayLong> CapeArrayLong_out;
  

  class  CapeArrayLong
    : public
        ::TAO::unbounded_value_sequence< CapeLong>
  {
  public:
    CapeArrayLong () = default;
    CapeArrayLong (::CORBA::ULong max);
    CapeArrayLong (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Long* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayLong (const CapeArrayLong &) = default;
    CapeArrayLong (CapeArrayLong &&) = default;
    CapeArrayLong& operator= (const CapeArrayLong &) = default;
    CapeArrayLong& operator= (CapeArrayLong &&) = default;
    virtual ~CapeArrayLong () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayLong_var;
    using _out_type = CapeArrayLong_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayLong;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Float CapeFloat;
  typedef ::CORBA::Float_out CapeFloat_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeFloat;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYFLOAT_CH_)
#define _SQPSOLVER_CAPEARRAYFLOAT_CH_

  class CapeArrayFloat;
  typedef ::TAO_FixedSeq_Var_T<CapeArrayFloat> CapeArrayFloat_var;
  typedef ::TAO_Seq_Out_T<CapeArrayFloat> CapeArrayFloat_out;
  

  class  CapeArrayFloat
    : public
        ::TAO::unbounded_value_sequence< CapeFloat>
  {
  public:
    CapeArrayFloat () = default;
    CapeArrayFloat (::CORBA::ULong max);
    CapeArrayFloat (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Float* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayFloat (const CapeArrayFloat &) = default;
    CapeArrayFloat (CapeArrayFloat &&) = default;
    CapeArrayFloat& operator= (const CapeArrayFloat &) = default;
    CapeArrayFloat& operator= (CapeArrayFloat &&) = default;
    virtual ~CapeArrayFloat () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayFloat_var;
    using _out_type = CapeArrayFloat_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayFloat;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Double CapeDouble;
  typedef ::CORBA::Double_out CapeDouble_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeDouble;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYDOUBLE_CH_)
#define _SQPSOLVER_CAPEARRAYDOUBLE_CH_

  class CapeArrayDouble;
  typedef ::TAO_FixedSeq_Var_T<CapeArrayDouble> CapeArrayDouble_var;
  typedef ::TAO_Seq_Out_T<CapeArrayDouble> CapeArrayDouble_out;
  

  class  CapeArrayDouble
    : public
        ::TAO::unbounded_value_sequence< CapeDouble>
  {
  public:
    CapeArrayDouble () = default;
    CapeArrayDouble (::CORBA::ULong max);
    CapeArrayDouble (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Double* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayDouble (const CapeArrayDouble &) = default;
    CapeArrayDouble (CapeArrayDouble &&) = default;
    CapeArrayDouble& operator= (const CapeArrayDouble &) = default;
    CapeArrayDouble& operator= (CapeArrayDouble &&) = default;
    virtual ~CapeArrayDouble () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayDouble_var;
    using _out_type = CapeArrayDouble_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayDouble;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:399

  typedef char * CapeString;
  typedef ::CORBA::String_var CapeString_var;
  typedef ::CORBA::String_out CapeString_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeString;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYSTRING_CH_)
#define _SQPSOLVER_CAPEARRAYSTRING_CH_

  class CapeArrayString;
  typedef ::TAO_VarSeq_Var_T<CapeArrayString> CapeArrayString_var;
  typedef ::TAO_Seq_Out_T<CapeArrayString> CapeArrayString_out;
  

  class  CapeArrayString
    : public
        ::TAO::unbounded_basic_string_sequence<char>
  {
  public:
    CapeArrayString () = default;
    CapeArrayString (::CORBA::ULong max);
    CapeArrayString (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer,
      ::CORBA::Boolean release = false);
    CapeArrayString (const CapeArrayString &) = default;
    CapeArrayString (CapeArrayString &&) = default;
    CapeArrayString& operator= (const CapeArrayString &) = default;
    CapeArrayString& operator= (CapeArrayString &&) = default;
    virtual ~CapeArrayString () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayString_var;
    using _out_type = CapeArrayString_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayString;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Any CapeVariant;
  typedef ::CORBA::Any_ptr CapeVariant_ptr;
  typedef ::CORBA::Any_var CapeVariant_var;
  typedef ::CORBA::Any_out CapeVariant_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeVariant;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYVARIANT_CH_)
#define _SQPSOLVER_CAPEARRAYVARIANT_CH_

  class CapeArrayVariant;
  typedef ::TAO_VarSeq_Var_T<CapeArrayVariant> CapeArrayVariant_var;
  typedef ::TAO_Seq_Out_T<CapeArrayVariant> CapeArrayVariant_out;
  

  class  CapeArrayVariant
    : public
        ::TAO::unbounded_value_sequence< CapeVariant>
  {
  public:
    CapeArrayVariant () = default;
    CapeArrayVariant (::CORBA::ULong max);
    CapeArrayVariant (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Any* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayVariant (const CapeArrayVariant &) = default;
    CapeArrayVariant (CapeArrayVariant &&) = default;
    CapeArrayVariant& operator= (const CapeArrayVariant &) = default;
    CapeArrayVariant& operator= (CapeArrayVariant &&) = default;
    virtual ~CapeArrayVariant () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayVariant_var;
    using _out_type = CapeArrayVariant_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayVariant;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typedef\typedef_ch.cpp:366

  typedef ::CORBA::Object CapeInterface;
  typedef ::CORBA::Object_ptr CapeInterface_ptr;
  typedef ::CORBA::Object_var CapeInterface_var;
  typedef ::CORBA::Object_out CapeInterface_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeInterface;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYINTERFACE_CH_)
#define _SQPSOLVER_CAPEARRAYINTERFACE_CH_

  class CapeArrayInterface;
  typedef ::TAO_VarSeq_Var_T<CapeArrayInterface> CapeArrayInterface_var;
  typedef ::TAO_Seq_Out_T<CapeArrayInterface> CapeArrayInterface_out;
  

  class  CapeArrayInterface
    : public
        ::TAO::unbounded_object_reference_sequence<
            CapeInterface,
            CapeInterface_var
          >
  {
  public:
    CapeArrayInterface () = default;
    CapeArrayInterface (::CORBA::ULong max);
    CapeArrayInterface (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Object_ptr* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayInterface (const CapeArrayInterface &) = default;
    CapeArrayInterface (CapeArrayInterface &&) = default;
    CapeArrayInterface& operator= (const CapeArrayInterface &) = default;
    CapeArrayInterface& operator= (CapeArrayInterface &&) = default;
    virtual ~CapeArrayInterface () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayInterface_var;
    using _out_type = CapeArrayInterface_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayInterface;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_exception\exception_ch.cpp:40

  

  class  CapeException : public ::CORBA::UserException
  {
  public:
    SqpSolver::CapeLong type;
    SqpSolver::CapeLong minus;
    SqpSolver::CapeLong completed;
    ::TAO::String_Manager idlmethod;
    ::TAO::String_Manager explanation;

    CapeException ();
    CapeException (const CapeException &);
    ~CapeException () = default;

    CapeException &operator= (const CapeException &);

    static void _tao_any_destructor (void *);

    static CapeException *_downcast (::CORBA::Exception *);
    static const CapeException *_downcast (::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc ();

    virtual ::CORBA::Exception *_tao_duplicate () const;

    virtual void _raise () const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_exception\exception_ctor.cpp:50

    

    CapeException (
        SqpSolver::CapeLong _tao_type,
        SqpSolver::CapeLong _tao_minus,
        SqpSolver::CapeLong _tao_completed,
        const char * _tao_idlmethod,
        const char * _tao_explanation);

    virtual ::CORBA::TypeCode_ptr _tao_type () const;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeException;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:258

  

  struct CapePublicParameter;
  using CapePublicParameter_var = ::TAO_Var_Var_T<CapePublicParameter>;
  using CapePublicParameter_out = ::TAO_Out_T<CapePublicParameter>;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct  CapePublicParameter
  {
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapePublicParameter_var;
    using _out_type = CapePublicParameter_out;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    ::TAO::String_Manager description;
    SqpSolver::CapeLong lowerBound;
    SqpSolver::CapeLong upperBound;
    SqpSolver::CapeVariant defaultValue;
    SqpSolver::CapeVariant currentValue;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapePublicParameter;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_CAPEARRAYPUBLICPARAMETER_CH_)
#define _SQPSOLVER_CAPEARRAYPUBLICPARAMETER_CH_

  class CapeArrayPublicParameter;
  typedef ::TAO_VarSeq_Var_T<CapeArrayPublicParameter> CapeArrayPublicParameter_var;
  typedef ::TAO_Seq_Out_T<CapeArrayPublicParameter> CapeArrayPublicParameter_out;
  

  class  CapeArrayPublicParameter
    : public
        ::TAO::unbounded_value_sequence< CapePublicParameter>
  {
  public:
    CapeArrayPublicParameter () = default;
    CapeArrayPublicParameter (::CORBA::ULong max);
    CapeArrayPublicParameter (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      CapePublicParameter* buffer,
      ::CORBA::Boolean release = false);
    CapeArrayPublicParameter (const CapeArrayPublicParameter &) = default;
    CapeArrayPublicParameter (CapeArrayPublicParameter &&) = default;
    CapeArrayPublicParameter& operator= (const CapeArrayPublicParameter &) = default;
    CapeArrayPublicParameter& operator= (CapeArrayPublicParameter &&) = default;
    virtual ~CapeArrayPublicParameter () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = CapeArrayPublicParameter_var;
    using _out_type = CapeArrayPublicParameter_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_CapeArrayPublicParameter;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_enum\enum_ch.cpp:39

  enum ParameterType
  {
    is_boolean,
    is_string,
    is_long,
    is_double
  };

  typedef ParameterType &ParameterType_out;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_ParameterType;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:258

  

  class ParameterValue;
  using ParameterValue_var = ::TAO_Var_Var_T<ParameterValue>;
  using ParameterValue_out = ::TAO_Out_T<ParameterValue>;

  class  ParameterValue
  {
  public:
    ParameterValue ();
    ParameterValue (const ParameterValue &);
    ~ParameterValue ();

    ParameterValue &operator= (const ParameterValue &);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union\discriminant_ch.cpp:98

    

    void _d ( ::CORBA::Short);
    ::CORBA::Short _d () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = ParameterValue_var;
    using _out_type = ParameterValue_out;

    static void _tao_any_destructor (void *);
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\public_ch.cpp:440

    

    void bValue ( SqpSolver::CapeBoolean);
    SqpSolver::CapeBoolean bValue () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\public_ch.cpp:568

    

    void sValue (char *);
    void sValue (const char *);
    void sValue (const ::CORBA::String_var&);
    const char *sValue () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\public_ch.cpp:440

    

    void lValue ( SqpSolver::CapeLong);
    SqpSolver::CapeLong lValue () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\public_ch.cpp:440

    

    void dValue ( SqpSolver::CapeDouble);
    SqpSolver::CapeDouble dValue () const;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union\union_ch.cpp:120

    

    void _default ();
  private:
    ::CORBA::Short disc_;

    union
    {
      // TAO_IDL - Generated from
      // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\private_ch.cpp:369

      
      SqpSolver::CapeBoolean bValue_;
      // TAO_IDL - Generated from
      // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\private_ch.cpp:464

      
      char *sValue_;
      // TAO_IDL - Generated from
      // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\private_ch.cpp:369

      
      SqpSolver::CapeLong lValue_;
      // TAO_IDL - Generated from
      // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union_branch\private_ch.cpp:369

      
      SqpSolver::CapeDouble dValue_;
    } u_;

    /// TAO extension - frees any allocated storage.
    void _reset ();
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_ParameterValue;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:258

  

  struct SolverParameterDescription;
  using SolverParameterDescription_var = ::TAO_Var_Var_T<SolverParameterDescription>;
  using SolverParameterDescription_out = ::TAO_Out_T<SolverParameterDescription>;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct  SolverParameterDescription
  {
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = SolverParameterDescription_var;
    using _out_type = SolverParameterDescription_out;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    SqpSolver::ParameterType type;
    ::TAO::String_Manager group;
    ::TAO::String_Manager domain;
    

    SqpSolver::ParameterValue value;
    ::TAO::String_Manager description;
    ::TAO::String_Manager fatherParameter;
    SqpSolver::CapeBoolean validCondition;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_SolverParameterDescription;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_SOLVERPARAMETERDESCRIPTIONSEQ_CH_)
#define _SQPSOLVER_SOLVERPARAMETERDESCRIPTIONSEQ_CH_

  class SolverParameterDescriptionSeq;
  typedef ::TAO_VarSeq_Var_T<SolverParameterDescriptionSeq> SolverParameterDescriptionSeq_var;
  typedef ::TAO_Seq_Out_T<SolverParameterDescriptionSeq> SolverParameterDescriptionSeq_out;
  

  class  SolverParameterDescriptionSeq
    : public
        ::TAO::unbounded_value_sequence< SolverParameterDescription>
  {
  public:
    SolverParameterDescriptionSeq () = default;
    SolverParameterDescriptionSeq (::CORBA::ULong max);
    SolverParameterDescriptionSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      SolverParameterDescription* buffer,
      ::CORBA::Boolean release = false);
    SolverParameterDescriptionSeq (const SolverParameterDescriptionSeq &) = default;
    SolverParameterDescriptionSeq (SolverParameterDescriptionSeq &&) = default;
    SolverParameterDescriptionSeq& operator= (const SolverParameterDescriptionSeq &) = default;
    SolverParameterDescriptionSeq& operator= (SolverParameterDescriptionSeq &&) = default;
    virtual ~SolverParameterDescriptionSeq () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = SolverParameterDescriptionSeq_var;
    using _out_type = SolverParameterDescriptionSeq_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_SolverParameterDescriptionSeq;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:258

  

  struct SolverParameter;
  using SolverParameter_var = ::TAO_Var_Var_T<SolverParameter>;
  using SolverParameter_out = ::TAO_Out_T<SolverParameter>;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct  SolverParameter
  {
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = SolverParameter_var;
    using _out_type = SolverParameter_out;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager name;
    

    SqpSolver::ParameterValue value;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_SolverParameter;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_SOLVERPARAMETERSEQ_CH_)
#define _SQPSOLVER_SOLVERPARAMETERSEQ_CH_

  class SolverParameterSeq;
  typedef ::TAO_VarSeq_Var_T<SolverParameterSeq> SolverParameterSeq_var;
  typedef ::TAO_Seq_Out_T<SolverParameterSeq> SolverParameterSeq_out;
  

  class  SolverParameterSeq
    : public
        ::TAO::unbounded_value_sequence< SolverParameter>
  {
  public:
    SolverParameterSeq () = default;
    SolverParameterSeq (::CORBA::ULong max);
    SolverParameterSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      SolverParameter* buffer,
      ::CORBA::Boolean release = false);
    SolverParameterSeq (const SolverParameterSeq &) = default;
    SolverParameterSeq (SolverParameterSeq &&) = default;
    SolverParameterSeq& operator= (const SolverParameterSeq &) = default;
    SolverParameterSeq& operator= (SolverParameterSeq &&) = default;
    virtual ~SolverParameterSeq () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = SolverParameterSeq_var;
    using _out_type = SolverParameterSeq_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_SolverParameterSeq;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:258

  

  struct SolutionResult;
  using SolutionResult_var = ::TAO_Var_Var_T<SolutionResult>;
  using SolutionResult_out = ::TAO_Out_T<SolutionResult>;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct  SolutionResult
  {
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = SolutionResult_var;
    using _out_type = SolutionResult_out;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager solverStatus;
    SqpSolver::CapeLong numOfIterations;
    SqpSolver::CapeLong CPUSeconds;
    SqpSolver::CapeLong numOfFunctionEvals;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_SolutionResult;

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

#if !defined (_SQPSOLVER_SOLUTIONRESULTSEQ_CH_)
#define _SQPSOLVER_SOLUTIONRESULTSEQ_CH_

  class SolutionResultSeq;
  typedef ::TAO_VarSeq_Var_T<SolutionResultSeq> SolutionResultSeq_var;
  typedef ::TAO_Seq_Out_T<SolutionResultSeq> SolutionResultSeq_out;
  

  class  SolutionResultSeq
    : public
        ::TAO::unbounded_value_sequence< SolutionResult>
  {
  public:
    SolutionResultSeq () = default;
    SolutionResultSeq (::CORBA::ULong max);
    SolutionResultSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      SolutionResult* buffer,
      ::CORBA::Boolean release = false);
    SolutionResultSeq (const SolutionResultSeq &) = default;
    SolutionResultSeq (SolutionResultSeq &&) = default;
    SolutionResultSeq& operator= (const SolutionResultSeq &) = default;
    SolutionResultSeq& operator= (SolutionResultSeq &&) = default;
    virtual ~SolutionResultSeq () = default;
    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = SolutionResultSeq_var;
    using _out_type = SolutionResultSeq_out;

    static void _tao_any_destructor (void *);
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_SolutionResultSeq;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_SQPSOLVER_ICAPEMINLP__VAR_OUT_CH_)
#define _SQPSOLVER_ICAPEMINLP__VAR_OUT_CH_

  class ICapeMINLP;
  using ICapeMINLP_ptr = ICapeMINLP*;
  using ICapeMINLP_var = TAO_Objref_Var_T<ICapeMINLP>;
  using ICapeMINLP_out = TAO_Objref_Out_T<ICapeMINLP>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  ICapeMINLP
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<ICapeMINLP>;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = ICapeMINLP_ptr;
    using _var_type = ICapeMINLP_var;
    using _out_type = ICapeMINLP_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static ICapeMINLP_ptr _duplicate (ICapeMINLP_ptr obj);

    static void _tao_release (ICapeMINLP_ptr obj);

    static ICapeMINLP_ptr _narrow (::CORBA::Object_ptr obj);
    static ICapeMINLP_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ICapeMINLP_ptr _nil ();

    virtual void GetMINLPSize (
      ::SqpSolver::CapeLong_out nv,
      ::SqpSolver::CapeLong_out niv,
      ::SqpSolver::CapeLong_out nlv,
      ::SqpSolver::CapeLong_out nliv,
      ::SqpSolver::CapeLong_out nc,
      ::SqpSolver::CapeLong_out nlc,
      ::SqpSolver::CapeLong_out nlz,
      ::SqpSolver::CapeLong_out nnz,
      ::SqpSolver::CapeLong_out nlzof,
      ::SqpSolver::CapeLong_out nnzof);

    virtual void GetMINLPStructure (
      const char * structuretype,
      ::SqpSolver::CapeArrayLong_out rowindex,
      ::SqpSolver::CapeArrayLong_out columnindex,
      ::SqpSolver::CapeArrayLong_out objindex);

    virtual void GetMINLPVariableNames (
      const ::SqpSolver::CapeArrayLong & vids,
      ::SqpSolver::CapeArrayString_out vnames);

    virtual void GetMINLPVariableDoubleAttribute (
      const ::SqpSolver::CapeArrayLong & vids,
      const char * attrib,
      ::SqpSolver::CapeArrayDouble_out values);

    virtual void GetMINLPVariableBounds (
      const ::SqpSolver::CapeArrayLong & vids,
      ::SqpSolver::CapeArrayDouble_out lb,
      ::SqpSolver::CapeArrayDouble_out ub);

    virtual void GetMINLPVariableValues (
      const ::SqpSolver::CapeArrayLong & vids,
      ::SqpSolver::CapeArrayDouble_out values);

    virtual void SetMINLPVariableValues (
      const ::SqpSolver::CapeArrayLong & vids,
      const ::SqpSolver::CapeArrayDouble & values);

    virtual void GetMINLPConstraintNames (
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayString_out cnames);

    virtual void GetMINLPConstraintBounds (
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayDouble_out lb,
      ::SqpSolver::CapeArrayDouble_out ub);

    virtual void GetMINLPConstraintDoubleAttribute (
      const ::SqpSolver::CapeArrayLong & cids,
      const char * attrib,
      ::SqpSolver::CapeArrayDouble_out values);

    virtual void GetMINLPNonlinearConstraintValues (
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayDouble_out values);

    virtual void GetMINLPConstraintDerivativeValues (
      const char * structtype,
      const ::SqpSolver::CapeArrayLong & cids,
      ::SqpSolver::CapeArrayDouble_out vals);

    virtual void GetMINLPNonlinearObjectiveFunctionValue (
      ::SqpSolver::CapeDouble_out value);

    virtual void GetMINLPObjectiveFunctionDerivativeValues (
      const char * stype,
      ::SqpSolver::CapeArrayDouble_out v);

    virtual void GetMINLPObjectiveFunctionDoubleAttribute (
      const char * attrib,
      ::SqpSolver::CapeDouble_out value);

    virtual void SetMINLPLagrangeMultipliers (
      const char * lmtype,
      const ::SqpSolver::CapeArrayLong & ids,
      const ::SqpSolver::CapeArrayDouble & values);

    virtual void GetMINLPLagrangeMultipliers (
      const char * lmtype,
      const ::SqpSolver::CapeArrayLong & ids,
      ::SqpSolver::CapeArrayDouble_out values);

    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    ICapeMINLP ();

    // Concrete non-local interface only.
    ICapeMINLP (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    ICapeMINLP (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~ICapeMINLP () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    ICapeMINLP (const ICapeMINLP &) = delete;
    ICapeMINLP (ICapeMINLP &&) = delete;
    ICapeMINLP &operator= (const ICapeMINLP &) = delete;
    ICapeMINLP &operator= (ICapeMINLP &&) = delete;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_ICapeMINLP;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_SQPSOLVER_ICAPEMINLPSYSTEM__VAR_OUT_CH_)
#define _SQPSOLVER_ICAPEMINLPSYSTEM__VAR_OUT_CH_

  class ICapeMINLPSystem;
  using ICapeMINLPSystem_ptr = ICapeMINLPSystem*;
  using ICapeMINLPSystem_var = TAO_Objref_Var_T<ICapeMINLPSystem>;
  using ICapeMINLPSystem_out = TAO_Objref_Out_T<ICapeMINLPSystem>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  ICapeMINLPSystem
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<ICapeMINLPSystem>;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = ICapeMINLPSystem_ptr;
    using _var_type = ICapeMINLPSystem_var;
    using _out_type = ICapeMINLPSystem_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static ICapeMINLPSystem_ptr _duplicate (ICapeMINLPSystem_ptr obj);

    static void _tao_release (ICapeMINLPSystem_ptr obj);

    static ICapeMINLPSystem_ptr _narrow (::CORBA::Object_ptr obj);
    static ICapeMINLPSystem_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ICapeMINLPSystem_ptr _nil ();

    virtual void GetParameters (
      ::SqpSolver::SolverParameterDescriptionSeq_out parameters);

    virtual void Solve ();

    virtual void SetParameters (
      const ::SqpSolver::SolverParameterDescriptionSeq & parameters);

    virtual void SetProblemID (
      ::SqpSolver::CapeLong id);

    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    ICapeMINLPSystem ();

    // Concrete non-local interface only.
    ICapeMINLPSystem (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    ICapeMINLPSystem (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~ICapeMINLPSystem () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    ICapeMINLPSystem (const ICapeMINLPSystem &) = delete;
    ICapeMINLPSystem (ICapeMINLPSystem &&) = delete;
    ICapeMINLPSystem &operator= (const ICapeMINLPSystem &) = delete;
    ICapeMINLPSystem &operator= (ICapeMINLPSystem &&) = delete;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_ICapeMINLPSystem;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_SQPSOLVER_ICAPEMINLPSOLVERMANAGER__VAR_OUT_CH_)
#define _SQPSOLVER_ICAPEMINLPSOLVERMANAGER__VAR_OUT_CH_

  class ICapeMINLPSolverManager;
  using ICapeMINLPSolverManager_ptr = ICapeMINLPSolverManager*;
  using ICapeMINLPSolverManager_var = TAO_Objref_Var_T<ICapeMINLPSolverManager>;
  using ICapeMINLPSolverManager_out = TAO_Objref_Out_T<ICapeMINLPSolverManager>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  ICapeMINLPSolverManager
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<ICapeMINLPSolverManager>;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = ICapeMINLPSolverManager_ptr;
    using _var_type = ICapeMINLPSolverManager_var;
    using _out_type = ICapeMINLPSolverManager_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static ICapeMINLPSolverManager_ptr _duplicate (ICapeMINLPSolverManager_ptr obj);

    static void _tao_release (ICapeMINLPSolverManager_ptr obj);

    static ICapeMINLPSolverManager_ptr _narrow (::CORBA::Object_ptr obj);
    static ICapeMINLPSolverManager_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ICapeMINLPSolverManager_ptr _nil ();

    virtual void CreateMINLPSystem (
      ::SqpSolver::ICapeMINLP_ptr theMINLP,
      ::SqpSolver::ICapeMINLPSystem_out theMINLPSystem);

    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    ICapeMINLPSolverManager ();

    // Concrete non-local interface only.
    ICapeMINLPSolverManager (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    ICapeMINLPSolverManager (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~ICapeMINLPSolverManager () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    ICapeMINLPSolverManager (const ICapeMINLPSolverManager &) = delete;
    ICapeMINLPSolverManager (ICapeMINLPSolverManager &&) = delete;
    ICapeMINLPSolverManager &operator= (const ICapeMINLPSolverManager &) = delete;
    ICapeMINLPSolverManager &operator= (ICapeMINLPSolverManager &&) = delete;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_ICapeMINLPSolverManager;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_SQPSOLVER_ISOLVERPARAMETERTUNER__VAR_OUT_CH_)
#define _SQPSOLVER_ISOLVERPARAMETERTUNER__VAR_OUT_CH_

  class ISolverParameterTuner;
  using ISolverParameterTuner_ptr = ISolverParameterTuner*;
  using ISolverParameterTuner_var = TAO_Objref_Var_T<ISolverParameterTuner>;
  using ISolverParameterTuner_out = TAO_Objref_Out_T<ISolverParameterTuner>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  ISolverParameterTuner
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<ISolverParameterTuner>;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = ISolverParameterTuner_ptr;
    using _var_type = ISolverParameterTuner_var;
    using _out_type = ISolverParameterTuner_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static ISolverParameterTuner_ptr _duplicate (ISolverParameterTuner_ptr obj);

    static void _tao_release (ISolverParameterTuner_ptr obj);

    static ISolverParameterTuner_ptr _narrow (::CORBA::Object_ptr obj);
    static ISolverParameterTuner_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ISolverParameterTuner_ptr _nil ();

    virtual void SetParameterTuningTask (
      const ::SqpSolver::SolverParameterDescriptionSeq & parameterList,
      ::SqpSolver::CapeLong numOfOptCases);

    virtual void GetNewParameters (
      const ::SqpSolver::SolutionResultSeq & solutionResult,
      const char * method,
      ::SqpSolver::SolverParameterSeq_out newParamters);

    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    ISolverParameterTuner ();

    // Concrete non-local interface only.
    ISolverParameterTuner (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    ISolverParameterTuner (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~ISolverParameterTuner () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    ISolverParameterTuner (const ISolverParameterTuner &) = delete;
    ISolverParameterTuner (ISolverParameterTuner &&) = delete;
    ISolverParameterTuner &operator= (const ISolverParameterTuner &) = delete;
    ISolverParameterTuner &operator= (ISolverParameterTuner &&) = delete;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_ISolverParameterTuner;
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_SQPSOLVER_IINITIALVALUEFINDER__VAR_OUT_CH_)
#define _SQPSOLVER_IINITIALVALUEFINDER__VAR_OUT_CH_

  class IInitialValueFinder;
  using IInitialValueFinder_ptr = IInitialValueFinder*;
  using IInitialValueFinder_var = TAO_Objref_Var_T<IInitialValueFinder>;
  using IInitialValueFinder_out = TAO_Objref_Out_T<IInitialValueFinder>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  IInitialValueFinder
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<IInitialValueFinder>;
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = IInitialValueFinder_ptr;
    using _var_type = IInitialValueFinder_var;
    using _out_type = IInitialValueFinder_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static IInitialValueFinder_ptr _duplicate (IInitialValueFinder_ptr obj);

    static void _tao_release (IInitialValueFinder_ptr obj);

    static IInitialValueFinder_ptr _narrow (::CORBA::Object_ptr obj);
    static IInitialValueFinder_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static IInitialValueFinder_ptr _nil ();

    virtual void Initialize (
      ::SqpSolver::CapeLong numOfTotalVariables,
      ::SqpSolver::CapeLong numOfKeyVariables,
      const ::SqpSolver::CapeArrayLong & keyVariableIndices,
      const ::SqpSolver::CapeArrayLong & keyVarMeasurementIndices);

    virtual void GetInitialValue (
      const ::SqpSolver::CapeArrayDouble & keyVariableValues,
      const ::SqpSolver::CapeArrayDouble & keyVarMeasurementValues,
      ::SqpSolver::CapeArrayDouble_out newInitialValues);

    
    // TAO_IDL - Generated from
    // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    IInitialValueFinder ();

    // Concrete non-local interface only.
    IInitialValueFinder (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    IInitialValueFinder (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~IInitialValueFinder () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    IInitialValueFinder (const IInitialValueFinder &) = delete;
    IInitialValueFinder (IInitialValueFinder &&) = delete;
    IInitialValueFinder &operator= (const IInitialValueFinder &) = delete;
    IInitialValueFinder &operator= (IInitialValueFinder &&) = delete;
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_IInitialValueFinder;


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module SqpSolver
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayBoolean>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayBoolean,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayChar>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayChar,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayShort>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayShort,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayLong>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayLong,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayFloat>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayFloat,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayDouble>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayDouble,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayString>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayString,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayVariant>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayVariant,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayInterface>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayInterface,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::SqpSolver::CapePublicParameter>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapePublicParameter,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::CapeArrayPublicParameter>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::CapeArrayPublicParameter,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:889

  

  template<>
  class Arg_Traits< ::SqpSolver::ParameterType>
    : public
        Basic_Arg_Traits_T<
            ::SqpSolver::ParameterType,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:1041

  

  template<>
  class Arg_Traits< ::SqpSolver::ParameterValue>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::ParameterValue,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::SqpSolver::SolverParameterDescription>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::SolverParameterDescription,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::SolverParameterDescriptionSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::SolverParameterDescriptionSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::SqpSolver::SolverParameter>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::SolverParameter,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::SolverParameterSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::SolverParameterSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::SqpSolver::SolutionResult>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::SolutionResult,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:671

  

  template<>
  class Arg_Traits< ::SqpSolver::SolutionResultSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::SqpSolver::SolutionResultSeq,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ICAPEMINLP__ARG_TRAITS_)
#define _SQPSOLVER_ICAPEMINLP__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::SqpSolver::ICapeMINLP>
    : public Object_Arg_Traits_T<
        ::SqpSolver::ICapeMINLP_ptr,
        ::SqpSolver::ICapeMINLP_var,
        ::SqpSolver::ICapeMINLP_out,
        TAO::Objref_Traits<SqpSolver::ICapeMINLP>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ICAPEMINLPSYSTEM__ARG_TRAITS_)
#define _SQPSOLVER_ICAPEMINLPSYSTEM__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::SqpSolver::ICapeMINLPSystem>
    : public Object_Arg_Traits_T<
        ::SqpSolver::ICapeMINLPSystem_ptr,
        ::SqpSolver::ICapeMINLPSystem_var,
        ::SqpSolver::ICapeMINLPSystem_out,
        TAO::Objref_Traits<SqpSolver::ICapeMINLPSystem>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ICAPEMINLPSOLVERMANAGER__ARG_TRAITS_)
#define _SQPSOLVER_ICAPEMINLPSOLVERMANAGER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::SqpSolver::ICapeMINLPSolverManager>
    : public Object_Arg_Traits_T<
        ::SqpSolver::ICapeMINLPSolverManager_ptr,
        ::SqpSolver::ICapeMINLPSolverManager_var,
        ::SqpSolver::ICapeMINLPSolverManager_out,
        TAO::Objref_Traits<SqpSolver::ICapeMINLPSolverManager>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_ISOLVERPARAMETERTUNER__ARG_TRAITS_)
#define _SQPSOLVER_ISOLVERPARAMETERTUNER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::SqpSolver::ISolverParameterTuner>
    : public Object_Arg_Traits_T<
        ::SqpSolver::ISolverParameterTuner_ptr,
        ::SqpSolver::ISolverParameterTuner_var,
        ::SqpSolver::ISolverParameterTuner_out,
        TAO::Objref_Traits<SqpSolver::ISolverParameterTuner>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_SQPSOLVER_IINITIALVALUEFINDER__ARG_TRAITS_)
#define _SQPSOLVER_IINITIALVALUEFINDER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::SqpSolver::IInitialValueFinder>
    : public Object_Arg_Traits_T<
        ::SqpSolver::IInitialValueFinder_ptr,
        ::SqpSolver::IInitialValueFinder_var,
        ::SqpSolver::IInitialValueFinder_out,
        TAO::Objref_Traits<SqpSolver::IInitialValueFinder>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_SQPSOLVER_ICAPEMINLP__TRAITS_)
#define _SQPSOLVER_ICAPEMINLP__TRAITS_

  template<>
  struct  Objref_Traits< ::SqpSolver::ICapeMINLP>
  {
    static ::SqpSolver::ICapeMINLP_ptr duplicate (::SqpSolver::ICapeMINLP_ptr p);
    static void release (::SqpSolver::ICapeMINLP_ptr p);
    static ::SqpSolver::ICapeMINLP_ptr nil ();
    static ::CORBA::Boolean marshal (const ::SqpSolver::ICapeMINLP_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_SQPSOLVER_ICAPEMINLPSYSTEM__TRAITS_)
#define _SQPSOLVER_ICAPEMINLPSYSTEM__TRAITS_

  template<>
  struct  Objref_Traits< ::SqpSolver::ICapeMINLPSystem>
  {
    static ::SqpSolver::ICapeMINLPSystem_ptr duplicate (::SqpSolver::ICapeMINLPSystem_ptr p);
    static void release (::SqpSolver::ICapeMINLPSystem_ptr p);
    static ::SqpSolver::ICapeMINLPSystem_ptr nil ();
    static ::CORBA::Boolean marshal (const ::SqpSolver::ICapeMINLPSystem_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_SQPSOLVER_ICAPEMINLPSOLVERMANAGER__TRAITS_)
#define _SQPSOLVER_ICAPEMINLPSOLVERMANAGER__TRAITS_

  template<>
  struct  Objref_Traits< ::SqpSolver::ICapeMINLPSolverManager>
  {
    static ::SqpSolver::ICapeMINLPSolverManager_ptr duplicate (::SqpSolver::ICapeMINLPSolverManager_ptr p);
    static void release (::SqpSolver::ICapeMINLPSolverManager_ptr p);
    static ::SqpSolver::ICapeMINLPSolverManager_ptr nil ();
    static ::CORBA::Boolean marshal (const ::SqpSolver::ICapeMINLPSolverManager_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_SQPSOLVER_ISOLVERPARAMETERTUNER__TRAITS_)
#define _SQPSOLVER_ISOLVERPARAMETERTUNER__TRAITS_

  template<>
  struct  Objref_Traits< ::SqpSolver::ISolverParameterTuner>
  {
    static ::SqpSolver::ISolverParameterTuner_ptr duplicate (::SqpSolver::ISolverParameterTuner_ptr p);
    static void release (::SqpSolver::ISolverParameterTuner_ptr p);
    static ::SqpSolver::ISolverParameterTuner_ptr nil ();
    static ::CORBA::Boolean marshal (const ::SqpSolver::ISolverParameterTuner_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_SQPSOLVER_IINITIALVALUEFINDER__TRAITS_)
#define _SQPSOLVER_IINITIALVALUEFINDER__TRAITS_

  template<>
  struct  Objref_Traits< ::SqpSolver::IInitialValueFinder>
  {
    static ::SqpSolver::IInitialValueFinder_ptr duplicate (::SqpSolver::IInitialValueFinder_ptr p);
    static void release (::SqpSolver::IInitialValueFinder_ptr p);
    static ::SqpSolver::IInitialValueFinder_ptr nil ();
    static ::CORBA::Boolean marshal (const ::SqpSolver::IInitialValueFinder_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayBoolean &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayBoolean*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayBoolean *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayChar &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayChar*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayChar *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayShort &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayShort*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayShort *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayLong &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayLong*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayLong *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayFloat &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayFloat*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayFloat *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayDouble &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayDouble*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayDouble *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayString &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayString*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayString *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayVariant &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayVariant*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayVariant *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayInterface &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayInterface*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayInterface *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_exception\any_op_ch.cpp:36


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



 void operator<<= (::CORBA::Any &, const SqpSolver::CapeException &); // copying version
 void operator<<= (::CORBA::Any &, SqpSolver::CapeException*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SqpSolver::CapeException *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\any_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapePublicParameter &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapePublicParameter*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapePublicParameter *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::CapeArrayPublicParameter &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::CapeArrayPublicParameter*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::CapeArrayPublicParameter *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_enum\any_op_ch.cpp:31


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



 void operator<<= (::CORBA::Any &, SqpSolver::ParameterType);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SqpSolver::ParameterType &);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union\any_op_ch.cpp:36


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const SqpSolver::ParameterValue &); // copying version
 void operator<<= (::CORBA::Any &, SqpSolver::ParameterValue*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SqpSolver::ParameterValue *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\any_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::SolverParameterDescription &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::SolverParameterDescription*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::SolverParameterDescription *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::SolverParameterDescriptionSeq &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::SolverParameterDescriptionSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::SolverParameterDescriptionSeq *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\any_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::SolverParameter &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::SolverParameter*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::SolverParameter *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::SolverParameterSeq &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::SolverParameterSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::SolverParameterSeq *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\any_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::SolutionResult &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::SolutionResult*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::SolutionResult *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\any_op_ch.cpp:46




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, const ::SqpSolver::SolutionResultSeq &); // copying version
 void operator<<= (::CORBA::Any &, ::SqpSolver::SolutionResultSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SqpSolver::SolutionResultSeq *&);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, SqpSolver::ICapeMINLP_ptr); // copying
 void operator<<= (::CORBA::Any &, SqpSolver::ICapeMINLP_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SqpSolver::ICapeMINLP_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, SqpSolver::ICapeMINLPSystem_ptr); // copying
 void operator<<= (::CORBA::Any &, SqpSolver::ICapeMINLPSystem_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SqpSolver::ICapeMINLPSystem_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, SqpSolver::ICapeMINLPSolverManager_ptr); // copying
 void operator<<= (::CORBA::Any &, SqpSolver::ICapeMINLPSolverManager_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SqpSolver::ICapeMINLPSolverManager_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, SqpSolver::ISolverParameterTuner_ptr); // copying
 void operator<<= (::CORBA::Any &, SqpSolver::ISolverParameterTuner_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SqpSolver::ISolverParameterTuner_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, SqpSolver::IInitialValueFinder_ptr); // copying
 void operator<<= (::CORBA::Any &, SqpSolver::IInitialValueFinder_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SqpSolver::IInitialValueFinder_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayBoolean_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayBoolean_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayBoolean &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayBoolean &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayBoolean_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayChar_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayChar_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayChar &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayChar &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayChar_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayShort_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayShort_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayShort &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayShort &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayShort_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayLong_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayLong_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayLong &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayLong &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayLong_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayFloat_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayFloat_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayFloat &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayFloat &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayFloat_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayDouble_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayDouble_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayDouble &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayDouble &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayDouble_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayString_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayString_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayString &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayString &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayString_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayVariant_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayVariant_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayVariant &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayVariant &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayVariant_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayInterface_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayInterface_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayInterface &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayInterface &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayInterface_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_exception\cdr_op_ch.cpp:36


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::CapeException &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::CapeException &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::CapePublicParameter &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::CapePublicParameter &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_CapeArrayPublicParameter_H_
#define _TAO_CDR_OP_SqpSolver_CapeArrayPublicParameter_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::CapeArrayPublicParameter &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::CapeArrayPublicParameter &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_CapeArrayPublicParameter_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_enum\cdr_op_ch.cpp:33


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, SqpSolver::ParameterType _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, SqpSolver::ParameterType &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_union\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::ParameterValue &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::ParameterValue &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::SolverParameterDescription &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::SolverParameterDescription &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_SolverParameterDescriptionSeq_H_
#define _TAO_CDR_OP_SqpSolver_SolverParameterDescriptionSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::SolverParameterDescriptionSeq &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::SolverParameterDescriptionSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_SolverParameterDescriptionSeq_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::SolverParameter &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::SolverParameter &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_SolverParameterSeq_H_
#define _TAO_CDR_OP_SqpSolver_SolverParameterSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::SolverParameterSeq &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::SolverParameterSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_SolverParameterSeq_H_ */
// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::SolutionResult &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::SolutionResult &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_SqpSolver_SolutionResultSeq_H_
#define _TAO_CDR_OP_SqpSolver_SolutionResultSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const SqpSolver::SolutionResultSeq &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    SqpSolver::SolutionResultSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_SqpSolver_SolutionResultSeq_H_ */


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::ICapeMINLP_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::ICapeMINLP_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::ICapeMINLPSystem_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::ICapeMINLPSystem_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::ICapeMINLPSolverManager_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::ICapeMINLPSolverManager_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::ISolverParameterTuner_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::ISolverParameterTuner_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_visitor_interface\cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SqpSolver::IInitialValueFinder_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SqpSolver::IInitialValueFinder_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\Github\vcpkg\buildtrees\ace\x64-windows-rel\TAO\TAO_IDL\be\be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "SqpSolverC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

